### ISSUE TITLE
Can't get email from form for use in successful submission message

### ISSUE THREAD

**Issue by matthew-levan** [pbteja1998/remix-auth-email-link#4]
I'd like to store the email address from the submitted form and use it to display a helpful message like:

### Magic link sent to ${email}!

This message would be displayed after successful submission of the magic link login form, before the user actually clicks the magic link in his email. 

... but I don't see a way to do that right now without writing my own `.authenticate` function. Any help is appreciated. Thank you for creating this project from the old code!

**Comment by myleslinder** [comment]
Unfortunately it seems we can't call authenticate without a success redirect [as seen in the remix auth docs](https://github.com/sergiodxa/remix-auth#custom-redirect-url-based-on-the-user) and then commit the session and be able to use action data in the route because  there [would be no way to get the magic link to commit to the session](https://github.com/pbteja1998/remix-auth-email-link/blob/f3c6c1e5dc68a951b977d9b3990bf9b1737c5900/src/index.ts#L215) as that doesn't really work well or conform with the signature for `authenticate`. Possible options would be adding a config value for the key to set the user email on in the session (which may make sense given there's already ones for `emailField` and `sessionMagicLinkKey`), or provide access to the request (or session) in [the verify or sendEmail callbacks](https://github.com/pbteja1998/remix-auth-email-link/blob/f3c6c1e5dc68a951b977d9b3990bf9b1737c5900/src/index.ts#L293) so we could add whatever to the session from there. 

The way I ended up doing this for now was by cloning the request so that I could read the form data and also wrapping the call to `authenticate` in a try-catch. If the caught value is an instance of `Response` and it's status is 302 I get the session using the "Set-Cookie" header (otherwise I rethrow the value). If the session has a value for the magic link key then I set the email from the form data in a separate key on the session and return a newly constructed `redirect` with the same url from the caught response (and all other response init values) and add the "Set-Cookie" header with the newly committed session (that includes both the keys set by the call to `authenticate` and the value set to the key for the email).

If anyone has any better suggestions or sees any issues with the approach I'm taking please definitely let me know.

**Comment by pbteja1998** [comment]
Resolved by #25

**Comment by pbteja1998** [comment]
Live in `v1.5.0`
